name: Maven Package and Release

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
      repository-projects: write
      packages: write

    steps:
    - uses: actions/checkout@v4
      with:
        ref: main
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github
        settings-path: ${{ github.workspace }} 

    - name: Maven Release x GitHub Packages
      run: |
        git config --global user.name "cosad3s - Github Actions"
        git config --global user.email "cosad3s@outlook.com"
        mvn -B release:prepare release:perform
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - name: Get the new tag
      id: get_tag
      run: echo "::set-output name=tag::$(git describe --tags $(git rev-list --tags --max-count=1))"
  
    - name: Create the release
      uses: softprops/action-gh-release@v2
      with:
        name: Release ${{ steps.get_tag.outputs.tag }}
        tag_name: ${{ steps.get_tag.outputs.tag }}
        files: |
          target/salsa-jar-with-dependencies.jar
        make_latest: true
        token: ${{ github.token }}