name: Maven Package and Release

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
      repository-projects: write
      packages: write

    steps:
    - uses: actions/checkout@v4
      with:
        ref: main

    - name: Release
      uses: qcastel/github-actions-maven-release@v1.12.41
      env:
        JAVA_HOME: /usr/lib/jvm/java-17-openjdk/
      with:
        maven-args: "-Dmaven.javadoc.skip=true -DskipTests -DskipITs -Dmaven.deploy.skip=true"
        git-release-bot-name: "cosad3s (bot)"
        git-release-bot-email: "cosad3s@outlook.com"
        release-branch-name: main
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Get the new tag
      id: get_tag
      run: echo "::set-output name=tag::$(git describe --tags $(git rev-list --tags --max-count=1))"

    - name: Create the release
      uses: softprops/action-gh-release@v2
      with:
        name: Release ${{ steps.get_tag.outputs.tag }}
        tag_name: ${{ steps.get_tag.outputs.tag }}
        files: |
          target/salsa-jar-with-dependencies.jar
        make_latest: true
        token: ${{ github.token }}